# Análise dos dados de reembolso dos senadores - 2018

In [2]:
#importando as bibliotecas
import pandas as pd

In [7]:
#Carregar o arquivo csv
df = pd.read_csv('2018.csv',sep=';', encoding='latin1', skiprows=1, decimal=',')

df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO
0,2018,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,NaN,02/01/2018,Despesa com pagamento de aluguel de imóvel par...,6000.00
1,2018,1,ACIR GURGACZ,"Passagens aéreas, aquáticas e terrestres nacio...",63.764.211/0001-10,TRANSCONTINENTAL AGÊNCIA DE VIAGENS LTDA,M2CJMM,02/01/2018,"Companhia Aérea: AVIANCA, Localizador: M2CJMM....",274.99
2,2018,1,ACIR GURGACZ,"Passagens aéreas, aquáticas e terrestres nacio...",63.764.211/0001-10,TRANSCONTINENTAL AGÊNCIA DE VIAGENS LTDA,SFEXYF,02/01/2018,"Companhia Aérea: LATAM, Localizador: SFEXYF. P...",1094.29
3,2018,1,ACIR GURGACZ,"Passagens aéreas, aquáticas e terrestres nacio...",63.764.211/0001-10,TRANSCONTINENTAL AGÊNCIA DE VIAGENS LTDA,V64HTR,24/01/2018,"Companhia Aérea: AZUL, Localizador: V64HTR. Pa...",1553.99
4,2018,2,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,002/18,01/02/2018,Despesa com pagamento de aluguel de imóvel par...,6000.00

In [8]:
#verificar tamanhos e tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24492 entries, 0 to 24491
Data columns (total 10 columns):
ANO                  24492 non-null int64
MES                  24492 non-null int64
SENADOR              24492 non-null object
TIPO_DESPESA         24492 non-null object
CNPJ_CPF             24492 non-null object
FORNECEDOR           24492 non-null object
DOCUMENTO            23476 non-null object
DATA                 24492 non-null object
DETALHAMENTO         18882 non-null object
VALOR_REEMBOLSADO    24492 non-null float64
dtypes: float64(1), int64(2), object(7)
memory usage: 1.9+ MB

In [9]:
#Mostrar uma analise quantitativa dos dados
df.describe()

           ANO           MES  VALOR_REEMBOLSADO
count  24492.0  24492.000000       24492.000000
mean    2018.0      6.192226        1045.431215
std        0.0      3.305847        2718.840577
min     2018.0      1.000000           0.010000
25%     2018.0      3.000000         125.000000
50%     2018.0      6.000000         287.200000
75%     2018.0      9.000000        1032.005000
max     2018.0     12.000000      103900.000000

In [13]:
#Qual o total de reeembolso?
df['VALOR_REEMBOLSADO' ].sum()

25604701.33

In [14]:
#Quantos reembolsos foram solicitados por cada senador?
df['SENADOR'].value_counts()

EDUARDO LOPES                    864
PAULO BAUER                      824
WELLINGTON FAGUNDES              800
JOSÉ SERRA                       715
GLEISI HOFFMANN                  653
HUMBERTO COSTA                   648
LÍDICE DA MATA                   628
JOSÉ MEDEIROS                    598
FERNANDO BEZERRA COELHO          560
ARMANDO MONTEIRO                 550
PAULO PAIM                       547
JOÃO CAPIBERIBE                  539
ANA AMÉLIA                       495
RONALDO CAIADO                   486
JOSÉ PIMENTEL                    477
PEDRO CHAVES DOS SANTOS FILHO    440
EDUARDO AMORIM                   438
ROBERTO REQUIÃO                  436
PAULO ROCHA                      424
ROMERO JUCÁ                      415
FÁTIMA BEZERRA                   407
MARTA SUPLICY                    398
ROBERTO MUNIZ                    380
ZEZÉ PERRELLA                    371
WALDEMIR MOKA                    370
AIRTON SANDOVAL                  363
CÁSSIO CUNHA LIMA                362
DALIRIO BEBER                    361
JORGE VIANA                      356
VANESSA GRAZZIOTIN               350
                                ...
EDUARDO BRAGA                    133
OTTO ALENCAR                     132
MARIA DO CARMO ALVES             129
JOÃO ALBERTO SOUZA               125
ANTÔNIO CARLOS VALADARES         117
ACIR GURGACZ                     114
PASTOR BEL                       113
DAVI ALCOLUMBRE                  112
RUDSON LEITE                     111
HÉLIO JOSÉ                       109
JOSÉ AMAURI                      101
REDITARIO CASSOL                  87
GUARACY SILVEIRA                  79
SÉRGIO PETECÃO                    75
KÁTIA ABREU                       72
SÉRGIO DE CASTRO                  66
RODRIGUES PALMA                   62
GIVAGO TENÓRIO                    57
WALTER PINHEIRO                   51
VICENTINHO ALVES                  51
EDISON LOBÃO                      49
ELBER BATALHA                     47
TASSO JEREISSATI                  44
IONE GUIMARÃES                    44
OMAR AZIZ                         42
ALVARO DIAS                       40
FERNANDO COLLOR                   27
JADER BARBALHO                    19
CRISTOVAM BUARQUE                 16
ZÉ SANTANA                         8
Name: SENADOR, Length: 91, dtype: int64

In [16]:
# Quanto cada senador solicitou de reembolso em 2018?
df.groupby('SENADOR')['VALOR_REEMBOLSADO'].sum().sort_values(ascending=False)

SENADOR
EDUARDO BRAGA                    529599.18
VANESSA GRAZZIOTIN               515969.63
JOÃO CAPIBERIBE                  513333.90
ÂNGELA PORTELA                   485806.44
OMAR AZIZ                        484143.98
CIRO NOGUEIRA                    455942.09
ROMERO JUCÁ                      454526.97
GLADSON CAMELI                   443981.70
FERNANDO COLLOR                  435944.08
JORGE VIANA                      430121.30
JOÃO ALBERTO SOUZA               429438.67
HUMBERTO COSTA                   427887.25
GARIBALDI ALVES FILHO            418031.85
WELLINGTON FAGUNDES              417778.67
PAULO PAIM                       415787.11
ARMANDO MONTEIRO                 415294.82
JOSÉ MEDEIROS                    411414.35
PAULO ROCHA                      405973.91
JOSÉ PIMENTEL                    405661.25
FLEXA RIBEIRO                    405371.13
VALDIR RAUPP                     405234.22
CÁSSIO CUNHA LIMA                398600.17
MAGNO MALTA                      397409.37
ROBERTO ROCHA                    386876.10
LINDBERGH FARIAS                 379909.54
PEDRO CHAVES DOS SANTOS FILHO    379386.06
ROSE DE FREITAS                  378182.77
RAIMUNDO LIRA                    375386.72
RANDOLFE RODRIGUES               373214.08
FERNANDO BEZERRA COELHO          367535.16
                                   ...
DALIRIO BEBER                    213061.41
LÚCIA VÂNIA                      212556.52
ANTÔNIO CARLOS VALADARES         212072.07
KÁTIA ABREU                      205291.80
DÁRIO BERGER                     199500.30
TASSO JEREISSATI                 195793.53
OTTO ALENCAR                     183048.34
JOSÉ MARANHÃO                    177914.91
RENAN CALHEIROS                  169975.04
WILDER MORAIS                    159069.64
CIDINHO SANTOS                   156965.76
JOSÉ AMAURI                      150165.53
REDITARIO CASSOL                 149322.99
ANA AMÉLIA                       147226.50
MARIA DO CARMO ALVES             146810.60
ELBER BATALHA                    125533.35
SIMONE TEBET                     124102.62
PASTOR BEL                       123515.72
RUDSON LEITE                     123015.14
BENEDITO DE LIRA                 122405.46
GIVAGO TENÓRIO                    80164.46
SÉRGIO DE CASTRO                  54318.55
RODRIGUES PALMA                   52676.18
GUARACY SILVEIRA                  50430.40
JADER BARBALHO                    44323.47
ALVARO DIAS                       44037.88
WALTER PINHEIRO                   32733.67
CRISTOVAM BUARQUE                 32400.00
ZÉ SANTANA                        23300.67
IONE GUIMARÃES                    11379.91
Name: VALOR_REEMBOLSADO, Length: 91, dtype: float64

In [18]:
#Quais são os 5 maiores valores de reembolso?
df.nlargest(5, 'VALOR_REEMBOLSADO').T

,21225,21488,21491,22666,5573
ANO,2018,2018,2018,2018,2018
MES,12,11,12,12,12
SENADOR,ROSE DE FREITAS,SÉRGIO PETECÃO,SÉRGIO PETECÃO,VANESSA GRAZZIOTIN,EDUARDO LOPES
TIPO_DESPESA,Divulgação da atividade parlamentar,"Contratação de consultorias, assessorias, pesq...","Contratação de consultorias, assessorias, pesq...","Contratação de consultorias, assessorias, pesq...",Divulgação da atividade parlamentar
CNPJ_CPF,05.461.408/0001-84,22.233.033/0001-14,22.233.033/0001-14,28.916.527/0001-80,14.616.988/0001-22
FORNECEDOR,Grafitusa S/A,Reis Grafica e Comercio de Etiquetas Eireli ME,Reis Grafica e Comercio de Etiquetas Eireli ME,A MAQUINA SOLUCOES EM MIDIA LTDA ME,NG Comunicação Visual Ltda
DOCUMENTO,000009681,4193,000004252,048,00000714
DATA,29/03/2019,29/11/2018,17/12/2018,17/12/2018,05/12/2018
DETALHAMENTO,NaN,NaN,NaN,TRABALHOS TÉCNICOS DE APOIO AO EXERCICIO DO MA...,NaN
VALOR_REEMBOLSADO,103900,102000,102000,100000,66000

In [19]:
# vAMOS VER OS 5 MENOS REEMBOLSO
df.nsmallest(5,'VALOR_REEMBOLSADO').T

,3868,10161,10191,10196,10233
ANO,2018,2018,2018,2018,2018
MES,5,3,4,4,5
SENADOR,DÁRIO BERGER,JORGE VIANA,JORGE VIANA,JORGE VIANA,JORGE VIANA
TIPO_DESPESA,"Passagens aéreas, aquáticas e terrestres nacio...","Passagens aéreas, aquáticas e terrestres nacio...","Passagens aéreas, aquáticas e terrestres nacio...","Passagens aéreas, aquáticas e terrestres nacio...","Passagens aéreas, aquáticas e terrestres nacio..."
CNPJ_CPF,02.575.829/0001-48,33.937.681/0001-78,07.575.651/0001-59,33.937.681/0001-78,33.937.681/0001-78
FORNECEDOR,AVIANCA BRASIL,LATAM,GOL TRANSPORTES AÉREOS S/A,LATAM,LATAM
DOCUMENTO,K5RKJV,W4UUE7,ZHV36P,W6ZMK3,OZALEF
DATA,29/05/2018,21/03/2018,09/03/2018,17/04/2018,22/05/2018
DETALHAMENTO,"Companhia Aérea: AVIANCA, Localizador: K5RKJV....","Companhia Aérea: LATAM, Localizador: W4UUE7. P...","Companhia Aérea: GOL, Localizador: ZHV36P. Pas...","Companhia Aérea: LATAM, Localizador: W6ZMK3. P...","Companhia Aérea: LATAM, Localizador: OZALEF. P..."
VALOR_REEMBOLSADO,0.01,0.01,0.01,0.01,0.01

In [21]:
#quantidade de reeembolsos por tipos de despesas
df['TIPO_DESPESA'].value_counts()

Locomoção, hospedagem, alimentação, combustíveis e lubrificantes                                                                                                                                   10147
Passagens aéreas, aquáticas e terrestres nacionais                                                                                                                                                  5820
Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.                                                                                                            5042
Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos.      1761
Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar                                                               928
Divulgação da atividade parlamentar                                                                                                                                                                  750
Serviços de Segurança Privada                                                                                                                                                                         44
Name: TIPO_DESPESA, dtype: int64

In [33]:
# Quais são os valores totais por tipos de despesas?
df.groupby('TIPO_DESPESA')['VALOR_REEMBOLSADO'].sum() .sort_values(ascending=False)

TIPO_DESPESA
Passagens aéreas, aquáticas e terrestres nacionais                                                                                                                                                 6335284.94
Locomoção, hospedagem, alimentação, combustíveis e lubrificantes                                                                                                                                   5620092.84
Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.                                                                                                           5041438.25
Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar                                                             4966449.41
Divulgação da atividade parlamentar                                                                                                                                                                2568910.24
Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos.      900312.04
Serviços de Segurança Privada                                                                                                                                                                       172213.61
Name: VALOR_REEMBOLSADO, dtype: float64